name: 🦖

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8, 11 ]

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: '${{ runner.os }}-m2-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: '${{ runner.os }}-m2'

      - name: test
        run: mvn clean test --file pom.xml --batch-mode --errors --show-version
