name: 🦖

on:
  push:
    branches:
      - '*'

jobs:

  job:
    name: Java ${{ matrix.java }} on ${{ matrix.os }}

    strategy:
      matrix:
        java: [ 8, 11 ]
      fail-fast: false

    runs-on: 'ubuntu-latest'

    steps:

      - name: Git
        uses: actions/checkout@v2

      - name: Java
        uses: actions/setup-java@v2.1.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          check-latest: true

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: '${{ runner.os }}-gradle-${{ hashFiles(''**/*.gradle'') }}'
          restore-keys: '${{ runner.os }}-gradle'

      - name: Test
        run: mvn --batch-mode --show-version --errors test --file pom.xml
