name: 🦖

on:
  push:
    branches:
      - '*'

jobs:

  job:
    name: Java ${{ matrix.java }}

    strategy:
      matrix:
        java: [ 8, 11, 17 ]
      fail-fast: true

    runs-on: 'ubuntu-latest'

    steps:

      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Skip JVM config
        if: matrix.java == '8'
        run: rm -f .mvn/jvm.config

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          check-latest: true

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: '${{ runner.os }}-gradle-${{ hashFiles(''**/*.gradle'') }}'
          restore-keys: '${{ runner.os }}-gradle'

      - name: Maven Verify
        run: mvn --batch-mode --show-version --errors verify --file pom.xml
