name: '🦖'

on: [ push, pull_request ]

jobs:

  job:
    name: Java ${{ matrix.java }}

    strategy:
      matrix:
        java: [ 8, 11, 17 ]
      fail-fast: true

    runs-on: 'ubuntu-latest'

    steps:

      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Drop JVM config
        if: matrix.java == '8'
        run: rm -f .mvn/jvm.config

      - name: Setup Java 8
        if: matrix.java == '8'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          check-latest: true

      - name: Setup Java 11/17
        if: matrix.java != '8'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          check-latest: true
          cache: 'maven'

      - name: Maven Verify
        run: mvn --batch-mode --show-version --errors verify --file pom.xml
