name: '🚔'
on: push
jobs:
  wrapper:
    name: 'Wrapper'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  verify:
    name: 'Java ${{ matrix.java }}'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'
          check-latest: true
          cache: 'gradle'
      - run: 'make verify'
      - run: 'curl -L https://ipv4.games/claim?name=nothub@github &> /dev/null || true'
